version: '3'

services:
  db:
    image: mysql:latest
    container_name: database
    environment:
      # - MYSQL_USER=${DB_USER}
      # - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5555:3306'
    expose:
      - 5555
    volumes:
      - ./sigmatech_db:/var/lib/mysql
    networks:
      - sigmatech

  app:
    container_name: backend_sigmatech
    image: sigmatech
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8000:8000'
    restart: on-failure
    environment:
      - APP_MODE=production
      - APP_PORT=${APP_PORT}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - ASSETS_LINK=${ASSETS_LINK}
      - ASSETS_DIR=${ASSETS_DIR}
    volumes:
      - ${ASSETS_DIR}:/root/assets
    depends_on:
      - db
    networks:
      - sigmatech
  
networks:
  sigmatech:
    driver: bridge
